### ISSUE TITLE
Implement computer fire functionality

### ISSUE THREAD

**Issue by olsenme** [OSU-CS361-W17/group2_project1#11]
Implement User Story "As a player, I want the opponent to be able to fire at a square." From the user perspective, the test for successful implementation of this story will be a hit /miss marker being placed on the user's view of the opponent game board

**Comment by Makumasa** [comment]
My pull request to master from feature_place-ship branch implemented this successfully, with the computer generating a random point on the board that hasn't been fired on yet to target and the model being updated by having said point added to either ComputerHits or ComputerMisses depending on whether the model has a user's ship in that location. Additionally, this functionality was tested in the GameStatsController_Tests file.
