### ISSUE TITLE
Game board has no visual rows and columns

### ISSUE THREAD

**Issue by struthj** [OSU-CS361-W17/group2_project1#2]
I want a visual representation of rows and columns above the game board like a physical battleship game (i.e A-J rows, 1-10 columns).

That is, implement the user story "As a player, I want to see row and column numbers, similar to what’s displayed on a physical Battleship game board." A test from the user's perspective would be seeing the rows and column markers to the left and above the game grids, respectively.

**Comment by zainkai** [comment]
Completed, the Rows on the frontend are abstracted as A-J. However, when the JSON object is created it is still (For Rows and Columns) 1-10.
