### ISSUE TITLE
Currently, neither the user nor the computer can place ships on the board

### ISSUE THREAD

**Issue by Makumasa** [OSU-CS361-W17/group2_project1#3]
Implement functionality for the user to place ships on the game board and during game initialization have the computer place their own ships on the board. The JSON object should be edited to reflect the user's/computer's choices. This should be implemented before Friday (02/07/17) in time for the Project 1 due date.

Essentially, implement the user story "As a player, I want to place my ships so that I can start the game." From the user's perspective, this will involve the ships appearing on their grid view of the game board.

**Comment by struthj** [comment]
Completed, placeShip function returns updated GameStatsModel JSON object with placed ship. Using BaseBalleship model functions: setName which based on name sets name and length of ship
and, setOrientation which based on orientation string sets starting and ending LocationPoint for a ship.
, BattleshipController uses gson to return a created basebattleship model, and GameStatsModel.addShip() adds and updates game stats model, which is then serialized and returned as a JSON object using gson to the placeShip function which returns the JSON Game board to the front end  client logic.
