### ISSUE TITLE
Backend has no logic for firing.

### ISSUE THREAD

**Issue by zainkai** [OSU-CS361-W17/group2_project1#4]
Create the logic in the backend for the player to fire at enemy ships.

Essentially, implement the user story "As I player, I want to fire at my ships so that I can start the game" 

From the user's perspective, the successful implementation of this story would involve the game model being changed.

**Comment by olsenme** [comment]
I based my implementation off of the Joseph's code to create a Java object in the controller and then edit the model from within the game model class. I also turned the coordinates of the point into a usable point to check for the hits and misses
